on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Azure CLI
        uses: actions/setup-azure-cli@v4

      - name: Deploy web app to Azure
        uses: azure/cli@v2
        with:
          inlineScript: |
            az --version
            #az storage account create --name demospstoraccxyz --resource-group myresourcegroup --location westus2
