on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.2
        with:
          # ClientId of the Azure Service principal created.
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # TenantId of the Azure Service principal created.
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # Azure subscriptionId
          subscription-id: ${{ secrets.AZURE_UBSCRIPTION_ID }}
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2.2.6
        with:
          # Name of the Azure Web App
          app-name: demowebappxyz001
          
          # Enter the resource group name of the web app
          resource-group-name: sp-demo-rg
      - name: Deploy web app to Azure
        uses: Azure/cli@v1.0.8
        with:
          inlineScript: |
            az --version
            #az storage account create --name demospstoraccxyz --resource-group sp-demo-rg --location westus2
